### ISSUE TITLE
Plugins

### ISSUE THREAD

**Issue by avnercaleb** [cami-la/collections-java-api-2023#10]
Ola Camila!!

E meio fora do contexto, mas pode passar os plugins q usa no IntelliJ?

**Comment by cami-la** [comment]
Fora de contexto? Nadaaa. Estou à disposição! (:

- https://plugins.jetbrains.com/plugin/10080-rainbow-brackets
- https://plugins.jetbrains.com/plugin/11349-aws-toolkit
- https://plugins.jetbrains.com/plugin/7125-grep-console
- https://plugins.jetbrains.com/plugin/12118-hiberbee-theme
- https://plugins.jetbrains.com/plugin/15075-jpa-buddy
- https://plugins.jetbrains.com/plugin/12507-package-search

**Comment by avnercaleb** [comment]
Vlw!!!!!
