### ISSUE TITLE
Themes Intellij

### ISSUE THREAD

**Issue by joabepereira** [cami-la/collections-java-api-2023#25]
Olá Camila, 

Parabéns pelas aulas, estou gostando muito da sua didática.
Uma pergunta não muito técnica, que tema é esse que você esta usando no Intellij pra esse curso?

Obrigado :)

**Comment by cami-la** [comment]
Oi, amigo. 
Primeiramente obrigada pelo feedsback. Fico muito feliz que esteja gostando das aulas. <3

Segue o tema: https://plugins.jetbrains.com/plugin/12118-hiberbee-theme

Qualquer dúvida, é só falar. Não precisa necessariamente ser dúvida técnica não. hehe Bons estudos para nós. <3

**Comment by joabepereira** [comment]
Muito obrigado :)
