### ISSUE TITLE
Generate equal() and hashCode()

### ISSUE THREAD

**Issue by Matt-Gary** [cami-la/collections-java-api-2023#38]
Eu posso gerar equal() and hashCode() em Visual Studio Code?

**Comment by cami-la** [comment]
Oie, boa tarde. Pode sim! (:

No Vs Code:

1. Clica na classe com o botão direito
2. Escolhe a opção Source Action
3. Override/Implements methods...
4. Seleciona as opções equals() e hashcode()

**Comment by Matt-Gary** [comment]
muito obrigado !
