### ISSUE TITLE
LivrariaOnline

### ISSUE THREAD

**Issue by dcasimiro89** [cami-la/collections-java-api-2023#41]
Boa noite, Camila. Tudo bem?
Estou tentando fazer o desafio da LivrariaOnline, mas travei em uma parte.

![issue_LivrariaOnline](https://github.com/cami-la/collections-java-api-2023/assets/57038237/9c30e02a-b9fe-4c4a-bc18-806157ba060c)

Mesmo criando um Comparator utilizando Map.Entry:

```
class ComparatorPorPreco implements Comparator<Map.Entry<String, Livro>> {
    @Override
    public int compare(Map.Entry<String, Livro> l1, Map.Entry<String, Livro> l2) {
        return Double.compare(l1.getValue().getPreco(), l2.getValue().getPreco());
    }
}
```
 Achei que funcionaria passando como parâmetro, conforme imagem acima, mas está dando erro.
Olhando a sua resposta, você utilizou List + Collection.sort(), para fazer a ordenação.

Mas a minha dúvida é, não tem como utilizar o Comparator dentro do TreeMap diretamente? Ou só dessa forma mesmo que você fez?

Obrigado.

**Comment by dcasimiro89** [comment]
Oi, Camila, bom dia. Tudo bem?
Hoje pesquisando a fundo, acredito que compreendi a situação rsrs
Treemap ele só ordena pela chave e não por valor. Por isso foi necessário criar uma List e fazer uma cópia para fazer a ordenação.
Correto?

**Comment by cami-la** [comment]
Isso, @dcasimiro89. Acertou, isso mesmo. O `TreeMap` ele organiza a partir das chaves. Inclusive acho que falei isso nas aulas, mas talvez não tenha dado tanta ênfase. Desculpe, viu?

De qualquer forma, parabéns pelos estudos. Está fazendo direitinho os exercícios. (:

Sigo à disposição.

**Comment by dcasimiro89** [comment]
Imagina! Erro foi meu que deixei passar batido essa informação. Estava tentando forçar uma ordenação, onde não existe.

Muito obrigado pela resposta e pelo apoio =)
