### ISSUE TITLE
Duvida implementacao metodo obterProdutoMaiorQuantidadeValorTotalNoEstoque

### ISSUE THREAD

**Issue by VzinCoder** [cami-la/collections-java-api-2023#51]
"Retorna o produto que está em maior quantidade no estoque, considerando o valor total de cada produto (quantidade * preço)." No caso eu deveria retornar o produto que tem maior valor total e maior quantidade ou o contrario? exemplo: Produto A {preco:10,qtd:1} Produto B {preco 1,qtd:10} logo o algoritimo deveria retornar B pois além dele ter o maior total tambem tem a maior quantidade.  Sua implementação esta diferente

**Comment by cami-la** [comment]
Oi, @VzinCoder. Continua ainda com a dúvida?
