### ISSUE TITLE
Exception in thread "main" java.lang.NullPointerException

### ISSUE THREAD

**Issue by Leticiassb** [cami-la/collections-java-api-2023#56]
# Oi Camila, meu código esta dando erro e nao consigo resolver, consegue me ajudar?
![Screenshot_16](https://github.com/cami-la/collections-java-api-2023/assets/164404350/9c8a9e81-72bc-4276-8f32-1f0a35993de7)
![Screenshot_15](https://github.com/cami-la/collections-java-api-2023/assets/164404350/d87a71bd-d883-41a4-ad8a-781c76adf7fc)
![Screenshot_14](https://github.com/cami-la/collections-java-api-2023/assets/164404350/e9e4dcf0-eba3-4507-8960-c08d48433688)

**Comment by Leticiassb** [comment]
Consegui, estava criando a ArrayList como void, fiz a alteração e deu certo
![Screenshot_18](https://github.com/cami-la/collections-java-api-2023/assets/164404350/edecafff-086d-439b-a8ca-8c372e1e18e1)

**Comment by cami-la** [comment]
Parabéns, @Leticiassb. Bons estudos!
