### ISSUE TITLE
Sugestão

### ISSUE THREAD

**Issue by LarissaSilvaFernandes** [cami-la/collections-java-api-2023#58]
Oi Cami, tudo bem? Fiz o exercício do Carrinho de Compras do curso '**Conhecendo Collections Java**' que você passou como "lição de casa", e implementei o método `removerItem(String nome){}` usando `removeIf`, o qual foi introduzido na versão Java 8 da API de coleções.

```
  public void removerItem(String nome) {
        carrinhoDeComprasList.removeIf(item -> item.getNome().equalsIgnoreCase(nome));
    }
```
O método `removerItem `que utiliza `removeIf` creio que é uma abordagem mais clara e potencialmente mais eficiente para remover itens de uma lista com base em um critério específico, como o nome. Abraços!!!

**Comment by cami-la** [comment]
Oi, lindona. Boa noite. Tudo certinho e por aí?

Então o `removeIf()` ele usa o expressão lambda que eu ainda não tinha explicado nesta parte da aula. hehe Por isso não utilizei.

E também quando usado, ele altera direto a lista original sem criar uma lista temporaria como a abordagem que eu fiz. Às vezes precisamos preservar a lista original.

Mas é só questão de objetivo mesmo. Inclusive no meu dia a dia geralmente utilizo da forma que você fez, porque já me acostumei em usar o expressão lambda.

Bons estudos para nós!

**Comment by LarissaSilvaFernandes** [comment]
Boa noite Cami! Fico feliz pelo retorno e pela explicação.☺️

Em ter., 14 de mai. de 2024 às 18:36, Camila Cavalcante <
***@***.***> escreveu:
