### ISSUE TITLE
Me encontro com um erro no exemplo Ordenação  Pessoa

### ISSUE THREAD

**Issue by RafaelaLeandro** [cami-la/collections-java-api-2023#74]
Tentei buscar a resposta para esse erro em outros lugares mas não entendo bem o que deu errado, fiz o codigo exatamente como a Camila, mas um erro persiste em aparecer na hora de ordenar por idade. 
Erro na imagem a seguir:

![image](https://github.com/cami-la/collections-java-api-2023/assets/142805138/341429b1-f803-4db8-b31f-f8fe53ce0944)

**Comment by cami-la** [comment]
Oi Rafa, tudo certinho?

Me mostra como você criou essa classe de comparação que está dando erro.
Talvez ela receba algum parâmetro que você não está passando na criação do novo o objeto.

**Comment by RafaelaLeandro** [comment]
Dá até vergonha de dizer, mas copiei o código e colei em uma nova classe e funcionou. Enfim o eclipse.
Mas obrigada mesmo assim por oferecer auxilio, suas aulas são ótimas <3.

**Comment by cami-la** [comment]
Mas é assim mesmo. No começo nós erramos coisas "bobas" mesmo. Com o passar do tempo, nós vemos o erro de longe. hehe

Bons estudos para nós!
