### ISSUE TITLE
Erro com a classe TreeSet

### ISSUE THREAD

**Issue by jm-236** [cami-la/collections-java-api-2023#75]
Boa tarde, Camila.
No exercício de operações básicas com set envolvendo o conjunto de convidados, experimentei trocar o `HashSet` pelas outras duas classes que implementam `Set` (`TreeSet` e `LinkedHashSet`).

No caso da `TreeSet`, o programa teve esse erro:
![image](https://github.com/cami-la/collections-java-api-2023/assets/159437965/717094a5-d10a-40a4-85fc-0dd61abfe4cc)

Será que você sabe me dizer o motivo de somente com a `TreeSet` acontecer esse erro ?

**Comment by tayanne1** [comment]
Parece q o erro que vc está enfrentando ao usar TreeSet é causado pq a classe Convidado não implementa a interface Comparable. O TreeSet requer que seus elementos sejam comparáveis para mantê-los ordenados, o que significa que a classe dos elementos deve implementar "Comparable" ou você deve fornecer um Comparator ao TreeSet.
